### PR TITLE
Apply Text specific tests to subclasses

### PR DESCRIPTION
**Pull request by nCrazed**
Still a work in progress, but here are the things that I've changed so far:

* Added `tests` directory to `autoload-dev` to allow support test classes/traits.
* Bumped minimum supported PHP version to 5.4
* Applied all `Text` test cases to `Email` and `Password`

A nice side effective of replacing all code in these test files is that they get to have 4 spaces instead of tabs (to be inline with the non-test source code) for free. :+1: 

##### TODO

- [x] Remove 5.3 from travis php test targets
- [x] Apply HTML5 attribute (`required` etc.) tests to all relevant element classes
- [x] Add 5.6 and 7.0 to travis php test targtets

Related to issue #40

### CODE REVIEW

**Comment by adamwathan** [comment]
Looks great so far! Let me know when you're finished everything you'd like to add and I'll merge it in :+1:

**Comment by nCrazed** [comment]
Got distracted by XCOM2 :video_game: 

Should be done by tomorrow.

**Comment by nCrazed** [comment]
Fingers crossed.

**Comment by nCrazed** [comment]
While moving methods into the new trait, I replaced most of the equality assertions with regexp.The previous assertions expected specific attributes in a specific order which didn't always happen. Including attributes that are not part of the test.

The new assertions are probably far from perfect, but they should cover most invalid cases and be flexible enough as long as we test one attribute at a time

**Comment by nCrazed** [comment]
Ok, I am done tinkering with this :+1:

**Comment by adamwathan** [comment]
Merged, thanks!

**Pull request merged**
