### PR TITLE
Add conditional option

### PR DESCRIPTION
**Pull request by daguilarm**
Sometimes, we required from our form a conditional behaviour, like:

$builder->text('email')->disabled(($profile->isAdmin()) ? true : false);

### CODE REVIEW

**Comment by axyr** [comment]
I would realy like to see this merged!

**Comment by adamwathan** [comment]
@daguilarm Can you add tests for this? Will merge when there's tests, thanks 👍

**Comment by JesseLeite** [comment]
I'm proposing a similar solution in #110, though I think a bit more flexible as it's a magic method implementation.  Thoughts?

**Comment by axyr** [comment]
I want this so bad.....
I have shitloads of: 

```
@if($item->send_email)
    {!! BootForm::textarea('Message', 'message')->addClass('emailmessage')->required() !!}
@else
    {!! BootForm::textarea('Message', 'message')->addClass('emailmessage') !!}
@endif
```

**Comment by adamwathan** [comment]
Thanks for adding the tests! What do we think the expected behavior should be if someone did something like:

`Form::text('name')->required()->required(false)`

Right now, it looks like this field would still be required. What do you think?

@JesseLeite I think I'm going to add the behavior from this PR even if we do add the magic method style you suggested in your PR, but we can consider the changes you've proposed separately. My instinct is that I don't love stuff that magically looks for substrings in method names (even bugs me when Laravel does it) but can still definitely discuss it.

**Comment by daguilarm** [comment]
public function hasAttribute($attribute)
    {
        return in_array($attribute, $this->attributes);
    }

    public function conditional($condition, $attribute)
    {
        if ($condition) {
            $this->setAttribute($attribute, $attribute);
        } else {
            if($this->hasAttribute($attribute)) {
                $this->removeAttribute($attribute);
            }
        }
    }

   public function required($condition = true)
    {
        $this->conditional($condition, __FUNCTION__);
        
        return $this;
    }

something like this?

**Comment by adamwathan** [comment]
I think maybe something like this:

```php
public function required($conditional = true)
{
    $this->setBooleanAttribute('required', $conditional);
    return $this;
}

protected function setBooleanAttribute($attribute, $value)
{
    if ($value) {
        $this->setAttribute($attribute, $attribute);
    } else {
        $this->removeAttribute($attribute);
    }
}
```

It's totally fine to call `removeAttribute` without first checking if it's there.

**Comment by daguilarm** [comment]
Perfect!!

**Comment by axyr** [comment]
Thank you all! I really missed this and i use this package a lot!!

**Comment by JesseLeite** [comment]
>@JesseLeite I think I'm going to add the behavior from this PR even if we do add the magic method style you suggested in your PR, but we can consider the changes you've proposed separately. My instinct is that I don't love stuff that magically looks for substrings in method names (even bugs me when Laravel does it) but can still definitely discuss it.

I love the magic method implementation in #110.  I understand what you mean on the substring `If` in the magic method name though.  I feel like #110's implementation was more flexible because it allowed for a conditional expression on any attribute setter, including magic attribute setters...

```php
Form::text('test')->wathan('sexy');
// <input type="text" name="test" wathan="sexy">

Form::text('test')->wathanIf(false, 'ugly');
// <input type="text" name="test">
```

This PR hardcodes the 'conditionalable' (oh geez) expression to attributes like `required`, `disabled`, etc.

...That said, if you want to close my other PR, I won't be sad :)

**Pull request merged**
