### PR TITLE
Method to get $data

### PR DESCRIPTION
**Pull request by sdebacker**
Hello Adam,

I propose this small change to make it possible to get data object. With this feature, we no longer have to make a child class of BoundData in https://github.com/Propaganistas/Laravel-Translatable-Bootforms package.

### CODE REVIEW

**Comment by adamwathan** [comment]
Looking at the Translatable Bootforms package to try and understand how this is being used in case there's a better solution, where is this `translate()` method defined? Is it expecting that you only bind models that implement the `translate` method?

https://github.com/Propaganistas/Laravel-Translatable-Bootforms/blob/master/src/Form/FormBuilder.php#L44

**Comment by adamwathan** [comment]
Also I think I would rather just add a `data` method like in the other package instead of making the first param optional in `get`. If you can make that change I'll merge this no biggie.

**Comment by sdebacker** [comment]
The translate method is here : https://github.com/dimsav/laravel-translatable/blob/master/src/Translatable/Translatable.php

I just created a data method. Thank you.

**Comment by sdebacker** [comment]
After the version bumping, I will make a PR on Propaganistas’ package.

**Comment by sdebacker** [comment]
Hello Adam, do you plan to release a v0.8.8 version that include this new data() method?

**Comment by adamwathan** [comment]
Whoops, sorry! Done!

**Comment by sdebacker** [comment]
Nice & Thanks.

**Pull request merged**
