### PR TITLE
Avoid to pass "_token" value through query string

### PR DESCRIPTION
**Pull request by irineujunior**
This patch prevent urls like http://blog.local/admin/posts/?_token=FGeYWnYVdmy7HEBret1OprY3IAYCzdNi3ESlINCG&status=active&name=test

### CODE REVIEW

**Comment by adamwathan** [comment]
Nice, was hesitant at first but obviously CSRF is not relevant for GET requests so why would we ever send this token? Thanks man!

**Comment by adamwathan** [comment]
Can you add a test similar to this one that shows GET forms don't include the token?

https://github.com/adamwathan/form/blob/master/tests/FormBuilderTest.php#L376-L382

**Comment by irineujunior** [comment]
Ok.. I'm not good with tests but I'll try. =)

**Comment by adamwathan** [comment]
It should be a pretty simple one, so good place to practice! :) If you have any issues let me know, happy to help.

**Comment by irineujunior** [comment]
Now sounds good.

**Comment by adamwathan** [comment]
Looks great, thanks again!

**Pull request merged**
