### PR TITLE
No error message with input named with brackets

### PR DESCRIPTION
**Pull request by sdebacker**
We have this input:

```html
<input type="text" name="customer[name]">
```

and this corresponding validation rule:

```php
$rules = [
    'customer.name' => 'required',
];
```

If empty input is submitted, we should have an error, but no error or message was set.

### CODE REVIEW

**Comment by sdebacker** [comment]
Added issue #37

**Comment by adamwathan** [comment]
Awesome this looks great, thanks! Could you add a test for the case you outlined in the initial comment? I can add it too if you don't have time. Will get it merged in then :+1:

**Comment by adamwathan** [comment]
Added your commits to this PR on a new branch, with comments there: #38

**Comment by sdebacker** [comment]
Hello Adam,

If you have the time, can you write the test ? I have little experience with testing and little time for the moment. 

Samuel

**Pull request closed without merging**
