### PR TITLE
Support for binding nested array/object/mixed via new BoundData object

### PR DESCRIPTION
**Pull request by JesseLeite**
This PR adds support for binding nested array/object/mixed data, using the new BoundData object helpers you helped me with.  I've added test coverage as well.

It's looking good, except for one regression...

screen shot 2016-03-25 at 1 06 32 am

**UPDATE:** I fixed this regression...

screen shot 2016-03-25 at 2 06 29 am

### CODE REVIEW

**Comment by JesseLeite** [comment]
Tests pass, ready for review!

Shakes :8ball:

**Comment by JesseLeite** [comment]
Tests pass, ready for review!

Shakes :8ball:

**Comment by adamwathan** [comment]
The only issue I see is using `false` as a sentinel value to represent "the object has no bound value for this field."

Try updating the test with this name in your test suite and it'll fail:

```php
    public function testBindingOnCheckboxTakesPrecedenceOverDefaultToChecked()
    {
        $object = (object) ['published' => 1];
        $this->form->bind($object);

        $expected  = '<input type="checkbox" name="published[]" value="1" checked="checked">';
        $result  = (string) $this->form->checkbox('published[]', 1);
        $this->assertEquals($expected, $result);

        $object = (object) ['published' => 0];
        $this->form->bind($object);

        $expected = '<input type="checkbox" name="published[]" value="1">';
        $result = (string) $this->form->checkbox('published[]', 1)->defaultToChecked();
        $this->assertEquals($expected, $result);

        $object = (object) ['published' => true];
        $this->form->bind($object);

        $expected = '<input type="checkbox" name="published[]" value="1" checked="checked">';
        $result = (string) $this->form->checkbox('published[]', 1);
        $this->assertEquals($expected, $result);

        $object = (object) ['published' => false];
        $this->form->bind($object);

        $expected = '<input type="checkbox" name="published[]" value="1">';
        $result = (string) $this->form->checkbox('published[]', 1)->defaultToChecked();
        $this->assertEquals($expected, $result);
    }
```

Unless we don't support booleans in bound data, which doesn't sound great to me. The only immediate solution that comes to mind is to throw an exception at the bottom of `dataGet` instead of returning false, and only return false in `has` if that exception gets thrown? Or come up with some unique sentinel value to return, but I haven't been able to think of anything that doesn't have potential issues.

**Comment by JesseLeite** [comment]
Yeah that test fails.  I'm not opposed to throwing an exception.  I could also create a class like `BoundDataFalse` for the purpose of type checking, instead of using a false boolean.  What would you call that, a value object or a null object?  Feels dirty though, because the class would be empty.  Throwing and catching an exception makes more sense I think...  Thoughts?

**Comment by adamwathan** [comment]
Alternatively could duplicate `dataGet` into something like `dataCheck` that just returns true instead of the target when it's found, or false at the end. Or a dreaded boolean flag to `dataGet` to toggle whether you want the value or just want to know if a value is present.

**Comment by JesseLeite** [comment]
Closing in favour of #92

**Pull request closed without merging**
