### PR TITLE
Ignore code coverage output files

### PR DESCRIPTION
**Pull request by nCrazed**

### CODE REVIEW

**Comment by nCrazed** [comment]
Do these files need to be tracked by git for the coverage to work?

**Comment by adamwathan** [comment]
Good idea to ignore that stuff, doesn't need to be tracked for coverage to work no. Looks like they've changed the minimum requirements for the coverage tool though. Can you update the `composer.json` requirement for the coveralls package to `^1.0` instead of `dev-master` and push again? Should get all the builds passing.

Thanks!

**Comment by nCrazed** [comment]
Looks like coveralls deprecated support for PHP < 5.5

> Problem 1

>    - Installation request for satooshi/php-coveralls dev-master -> satisfiable by satooshi/php-coveralls[dev-master].

>    - satooshi/php-coveralls dev-master requires php >=5.5 -> your PHP version (5.4.45) or config.platform.php" value does not satisfy that requirement.

**Comment by nCrazed** [comment]
Ok, will do

**Comment by nCrazed** [comment]
While we're on the topic, the `todo.md`, `.DS_Store` and `composer.phar` file are specific to your environment, but not this projects; `todo.md` and `composer.phar` are related to your personal workflow of keeping a todo file and composer binary in project directories, and `.DS_Store` is part of your OS.

You can ignore them for your self without affecting the projects that you work on by setting the [core.excludesFile](https://git-scm.com/docs/git-config) option in your global/user git configuration file.

I am not sure what that would be on Mac, but on linux that's usually `$HOME/.gitconfig` and it would looks something like this:

```ini
#$HOME/.gitconfig
[core]
    excludesfile = ~/.gitignore
```
```ini
#$HOME/.gitignore
todo.md
composer.phar
.DS_Store
```

**Comment by nCrazed** [comment]
Looks like there's an issue with coveralls treating 0.0% change as negative. 

https://github.com/lemurheavy/coveralls-public/issues/709

**Comment by adamwathan** [comment]
Yeah should update that for sure :) Thanks

**Comment by adamwathan** [comment]
Yeah not too worried about that :+1:

**Pull request merged**
